module.exports = {
  'Bench Press': { koeficijent: 0.65, format: 'barbell', reps_baza: 8 },
  'Incline Smith Bench Press': { koeficijent: 0.55, format: 'barbell', reps_baza: 8 },
  'Incline Dumbbell Press': { koeficijent: 0.45, format: 'dumbbell', reps_baza: 8 },
  'Incline Bench Press': { koeficijent: 0.5, format: 'barbell', reps_baza: 8 },
  'Butterfly Press': { koeficijent: 0.55, format: 'machine', reps_baza: 13 },
  'Machine Chest Press': { koeficijent: 0.45, format: 'machine', reps_baza: 13 },
  'Push-ups': { koeficijent: 0.2, format: 'bodyweight_reps', reps_baza: null },
  'Pull-ups': { koeficijent: 0.1, format: 'bodyweight_reps', reps_baza: null },
  'Barbell Rows': { koeficijent: 0.55, format: 'barbell', reps_baza: 13 },
  'Machine Rows': { koeficijent: 0.6, format: 'machine', reps_baza: 13 },
  'Lat Pulldown': { koeficijent: 0.65, format: 'machine', reps_baza: 13 },
  'Lat Flys': { koeficijent: 0.2, format: 'dumbbell', reps_baza: 13 },
  'Overhead Press': { koeficijent: 0.4, format: 'barbell', reps_baza: 8 },
  'Rear Delts': { koeficijent: 0.4, format: 'machine', reps_baza: 13 },
  'Cable Lat Flys': { koeficijent: 0.1, format: 'machine', reps_baza: 13 },
  'Bicep Curls': { koeficijent: 0.3, format: 'dumbbell', reps_baza: 13 },
  'Biceps Machine': { koeficijent: 0.35, format: 'machine', reps_baza: 13 },
  'Triceps Pushdown': { koeficijent: 0.25, format: 'machine', reps_baza: 13 },
  'Skullcrushers': { koeficijent: 0.15, format: 'barbell', reps_baza: 8 },
  'Bulgarian Squat': { koeficijent: 0.3, format: 'dumbbell', reps_baza: 8 },
  'Squat (Barbell)': { koeficijent: 0.65, format: 'barbell', reps_baza: 8 },
  'Quad Extensions': { koeficijent: 0.6, format: 'machine', reps_baza: 13 },
  'Leg Press': { koeficijent: 0.75, format: 'machine', reps_baza: 8 },
  'Hack Squat': { koeficijent: 0.75, format: 'machine', reps_baza: 8 },
  'Romanian Deadlift': { koeficijent: 0.8, format: 'barbell', reps_baza: 8 },
  'Hamstring Curls Machine': { koeficijent: 0.65, format: 'machine', reps_baza: 13 },
  'Calf Raises': { koeficijent: 0.4, format: 'machine', reps_baza: 13 },
  'Running (treadmill)': { koeficijent: 0.15, format: 'cardio_minutes', reps_baza: null },
  'Exercise Bike': { koeficijent: 0.1, format: 'cardio_minutes', reps_baza: null },
  'Stair Climber': { koeficijent: 0.15, format: 'cardio_minutes', reps_baza: null }
};
